# Generated by Django 4.1.7 on 2023-03-16 06:13

import account.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_cover_pic_alter_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_pic',
            field=models.ImageField(null=True, upload_to=account.models.User.cover_pic_upload),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 11, 58, 22, 900261)),
        ),
    ]
