# Generated by Django 4.1.5 on 2023-02-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply',
        ),
    ]
