# Generated by Django 4.1.5 on 2023-02-04 08:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_alter_downvotequestion_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downvoteanswer',
            unique_together={('user', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='downvotequestion',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='upvoteanswer',
            unique_together={('user', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='upvotequestion',
            unique_together={('user', 'question')},
        ),
    ]
