# Generated by Django 4.1.5 on 2023-02-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_downvoteanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvoteanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvote_answer', to='post.answer'),
        ),
    ]
